project:
  type: book
  output-dir: docs
bibliography: weighting_refs.bib
nocite: |
  @*
jupyter: nbstata

execute:
  echo: false
  warning: false
  message: false
  cache: false
  freeze: auto


book:
  title: "Statistical inference  with weights and survey design variables"
  subtitle: Practical guidelines using  UKDS datasets
  chapters:
    - index.qmd
    - 01_Basics.qmd
    - 02_Design-Based_Inference.qmd
    - 03_Real_world.qmd
    - 04_Statistical_Inference.qmd
    - 05_R.qmd
    - 06_SPSS.qmd
    - 07_Stata.qmd
    - 09_References.qmd
    - 08_Appendix.qmd



  sidebar:
    logo: "pics/UKDS_Logos_Col_Grey_300dpi.png"
    logo-href: http:// ukdataservice.ac.uk
    logo-alt: "UKDS homepage"
    style: "floating"
    

    # chapters:
    #   - href: index.qmd
    #     text: "Introduction"
    # 
    #   - href: 01_Basics.qmd
    #     text: "Basics"
    #   - href: 02_Design-Based_Inference.qmd
    #     text: "Design-based inference"
    #   - href: 03_Real_world.qmd
    #     text: "Real-world inference"
    #   - href: 04_Statistical_Inference.qmd
    #     text: "Inference in practice"
    #     
    #   - section: "Examples"
    #     contents:
    #       - href: 05_R.qmd
    #         text: "R"
    #       - href: 06_SPSS.qmd
    #         text: "SPSS"  
    #       - href: 07_Stata.qmd
    #         text: "Stata"

      # - href: 08_Appendix.qmd
      # - href: 09_References.qmd


format:
    html: 
      code-overflow: scroll
      code-line-numbers: true
      page-layout: full
      toc: true
      toc-location: right
      highlight-style: arrow-light
     # embed-resources: true
      smooth-scroll: true
      link-external-newwindow: true
      citations-hover: true
      footnotes-hover: true



mainfont: "Open Sans" 
sansfont: "Open Sans"
monofont: "Courier New"
monofontoptions: 'Scale=0.8'
pdf-engine: lualatex




